import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Building2, Clock3, MapPin, Plane, ShieldCheck } from 'lucide-react';
import { SiteShell, WhatsAppPill } from '@/components/site-shell';

const services = [
  { icon: Plane, number: '01', tag: 'AEROPUERTO', title: 'Llegue sin contratiempos', text: 'Traslados desde y hacia el aeropuerto de Calama, coordinados con el horario de su vuelo.' },
  { icon: MapPin, number: '02', tag: 'SAN PEDRO', title: 'El desierto a su ritmo', text: 'Viajes privados entre Calama y San Pedro de Atacama con conductores que conocen la ruta.' },
  { icon: Building2, number: '03', tag: 'EMPRESAS', title: 'Movilidad para su equipo', text: 'Traslados corporativos y a faenas mineras, adaptados a turnos y necesidades operativas.' },
];
export default function Home() {
  return <SiteShell><section className="hero home-hero"><div className="container hero-content"><span className="eyebrow eyebrow-gold"><span/> TRASLADOS EN CALAMA Y SAN PEDRO</span><h1>Su viaje comienza<br/>con <em>tranquilidad.</em></h1><p>Transporte privado desde Calama al aeropuerto, San Pedro de Atacama y faenas mineras. Puntualidad y experiencia local en cada recorrido.</p><div className="hero-actions"><Link href="/reservar" className="button button-yellow">Solicitar reserva <ArrowUpRight size={18}/></Link><Link href="/nosotros" className="text-link light">Conozca nuestro servicio <ArrowRight size={17}/></Link></div><div className="hero-proof"><span><ShieldCheck size={17}/> Más de 10 años de experiencia</span><span><Clock3 size={17}/> Traslados coordinados</span></div></div><div className="hero-index">01 / 03 <span/></div></section>
    <section className="intro-section section"><div className="container intro-grid"><div><span className="eyebrow">01 / QUIÉNES SOMOS</span><h2>Conocemos el camino.<br/><span>Usted disfruta el viaje.</span></h2></div><div className="intro-text"><p>En Martín Atacama Transfers conectamos personas y destinos en el norte de Chile. Cada traslado se planifica con atención a los horarios, las rutas y las condiciones del desierto.</p><p>Un equipo local, vehículos confortables y comunicación directa para que llegue a destino con confianza.</p><Link href="/nosotros" className="text-link">Más sobre nosotros <ArrowUpRight size={17}/></Link></div></div></section>
    <section className="services-section section"><div className="container"><div className="section-heading"><div><span className="eyebrow">02 / NUESTROS SERVICIOS</span><h2>El traslado que necesita,<br/><span>en el momento indicado.</span></h2></div><Link href="/reservar" className="text-link">Planificar mi traslado <ArrowUpRight size={17}/></Link></div><div className="service-grid">{services.map(s => <article className="service-card" key={s.number}><div className="service-top"><span>{s.number} / {s.tag}</span><s.icon size={26} strokeWidth={1.6}/></div><div><h3>{s.title}</h3><p>{s.text}</p><Link href="/reservar" aria-label={`Reservar ${s.tag.toLowerCase()}`}><ArrowUpRight size={21}/></Link></div></article>)}</div></div></section>
    <section className="feature-section"><div className="feature-image" role="img" aria-label="Rutas del desierto de Atacama"/><div className="feature-content"><span className="eyebrow eyebrow-gold">03 / EXPERIENCIA LOCAL</span><h2>El desierto se disfruta más cuando está en buenas manos.</h2><p>Con más de una década recorriendo la Región de Antofagasta, coordinamos traslados para pasajeros, turistas y empresas con conocimiento real del territorio.</p><div className="feature-stats"><div><strong>10+</strong><span>años de experiencia</span></div><div><strong>03</strong><span>destinos principales</span></div></div><Link href="/reservar" className="button button-outline">Organizar un traslado <ArrowUpRight size={17}/></Link></div></section>
    <section className="cta-strip"><div className="container cta-grid"><div><span className="eyebrow">SU PRÓXIMO VIAJE</span><h2>Cuéntenos dónde y cuándo.<br/>Nosotros nos encargamos del resto.</h2></div><Link href="/reservar" className="button button-dark">Solicitar reserva <ArrowUpRight size={18}/></Link></div></section><WhatsAppPill/></SiteShell>;
}
