'use client';
import { useState, type FormEvent } from 'react';
import { ArrowUpRight, CheckCircle2 } from 'lucide-react';

const options = ['Aeropuerto El Loa, Calama', 'Calama, centro', 'San Pedro de Atacama', 'Hotel / alojamiento', 'Faena minera', 'Otro punto'];
const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Santiago', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
export function BookingForm() {
  const [state, setState] = useState<'idle'|'sending'|'sent'>('idle'); const [error, setError] = useState(''); const [reference, setReference] = useState('');
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setError(''); setState('sending');
    const form = e.currentTarget; const data = Object.fromEntries(new FormData(form).entries());
    const payload = { ...data, consent: data.consent === 'on', passengers: Number(data.passengers) };
    try { const res = await fetch('/api/reservas', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await res.json(); if (!res.ok) throw new Error(result.error || 'No fue posible registrar la solicitud.'); setReference(result.reference); setState('sent'); form.reset(); }
    catch (err) { setError(err instanceof Error ? err.message : 'Ocurrió un error.'); setState('idle'); }
  }
  if (state === 'sent') return <div className="booking-success"><CheckCircle2 size={52}/><span className="eyebrow">SOLICITUD REGISTRADA</span><h2>Recibimos los datos de su viaje.</h2><p>Guarde este número de referencia. Nuestro equipo revisará la disponibilidad y se comunicará con usted para confirmar el traslado.</p><strong>{reference}</strong><button type="button" className="text-link" onClick={() => { setState('idle'); setReference(''); }}>Solicitar otro traslado →</button></div>;
  return <form onSubmit={submit} className="booking-form"><div className="form-group-title"><span>01</span><h3>Trayecto</h3></div><div className="form-grid"><label className="full">Tipo de servicio *<select name="service" required defaultValue=""><option value="" disabled>Seleccione un servicio</option><option value="aeropuerto">Aeropuerto</option><option value="san-pedro">Calama ↔ San Pedro de Atacama</option><option value="empresa">Empresa o faena minera</option><option value="otro">Otro traslado privado</option></select></label><label>Origen *<input name="origin" list="places" placeholder="¿Dónde lo recogemos?" required minLength={2} maxLength={120}/></label><label>Destino *<input name="destination" list="places" placeholder="¿Hacia dónde viaja?" required minLength={2} maxLength={120}/></label><datalist id="places">{options.map(o => <option key={o} value={o}/>)}</datalist></div><div className="form-group-title"><span>02</span><h3>Fecha y pasajeros</h3></div><div className="form-grid three"><label>Fecha del traslado *<input type="date" name="travelDate" min={today} required/></label><label>Horario de salida *<input type="time" name="travelTime" required/></label><label>Pasajeros *<input type="number" name="passengers" min={1} max={30} defaultValue={1} required/></label></div><div className="form-group-title"><span>03</span><h3>Sus datos de contacto</h3></div><div className="form-grid"><label>Nombre completo *<input name="passengerName" autoComplete="name" placeholder="Nombre y apellido" required minLength={2} maxLength={100}/></label><label>Teléfono / WhatsApp *<input name="phone" type="tel" autoComplete="tel" placeholder="+56 9 ..." required minLength={8} maxLength={30}/></label><label className="full">Correo electrónico *<input name="email" type="email" autoComplete="email" placeholder="nombre@correo.cl" required maxLength={160}/></label><label className="full">Información adicional<textarea name="notes" rows={4} maxLength={1000} placeholder="Número de vuelo, equipaje, necesidades especiales u otros detalles"/></label></div><label className="check-label"><input type="checkbox" name="consent" required/><span>Acepto que mis datos sean utilizados para gestionar esta solicitud y contactarme sobre el traslado. *</span></label><label className="honeypot" aria-hidden="true">Sitio web<input name="website" tabIndex={-1} autoComplete="off"/></label>{error && <p className="form-error" role="alert">{error}</p>}<button type="submit" className="button button-yellow submit-booking" disabled={state === 'sending'}>{state === 'sending' ? 'Registrando solicitud...' : 'Enviar solicitud de reserva'} <ArrowUpRight size={18}/></button><p className="form-disclaimer">El envío no garantiza disponibilidad ni confirma automáticamente el traslado.</p></form>;
}
