'use client';
import { useState, type FormEvent } from 'react';
import { ArrowUpRight } from 'lucide-react';
export function ContactForm() {
  const [state, setState] = useState<'idle'|'sending'|'sent'>('idle'); const [error, setError] = useState('');
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(''); setState('sending'); const form = e.currentTarget; const data = Object.fromEntries(new FormData(form).entries()); try { const res = await fetch('/api/contacto', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await res.json(); if (!res.ok) throw new Error(result.error || 'No fue posible enviar el mensaje.'); setState('sent'); form.reset(); } catch (err) { setError(err instanceof Error ? err.message : 'Ocurrió un error.'); setState('idle'); } }
  if (state === 'sent') return <div className="success-box"><h4>Mensaje recibido</h4><p>Su consulta quedó registrada. Nos comunicaremos con usted a la brevedad.</p><button type="button" onClick={() => setState('idle')} className="text-link">Enviar otro mensaje →</button></div>;
  return <form className="form-grid" onSubmit={submit}><label>Nombre completo<input name="name" autoComplete="name" required minLength={2} maxLength={100}/></label><label>Correo electrónico<input type="email" name="email" autoComplete="email" required maxLength={160}/></label><label>Teléfono / WhatsApp<input type="tel" name="phone" autoComplete="tel" required minLength={8} maxLength={30}/></label><label>Asunto<input name="subject" required minLength={2} maxLength={120}/></label><label className="full">Cuéntenos en qué podemos ayudarle<textarea name="message" rows={5} required minLength={10} maxLength={3000}/></label><label className="honeypot" aria-hidden="true">Sitio web<input name="website" tabIndex={-1} autoComplete="off"/></label>{error && <p className="form-error full" role="alert">{error}</p>}<button disabled={state === 'sending'} className="button button-yellow" type="submit">{state === 'sending' ? 'Enviando...' : 'Enviar mensaje'} <ArrowUpRight size={17}/></button></form>;
}
